[package]
name = "walletd-core"
version = "0.1.0"
edition = "2021"
description = "Core WalletD SDK functionality"
license = "MIT OR Apache-2.0"
repository = "https://github.com/walletd/walletd"

[dependencies]
serde = { workspace = true }
# Other dependencies unchanged