name: CI Fix

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Install protoc for Hedera
    - name: Install Protobuf
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
    
    - name: Build
      run: cargo build --all-features
