name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # FIX: Install protoc for Hedera
    - name: Install Protobuf Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
    
    - name: Run tests
      run: cargo test --all-features --verbose
      
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # FIX: Install protoc for Hedera
    - name: Install Protobuf Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings
      
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run rustfmt
      run: cargo fmt --all -- --check
      
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # FIX: Install protoc for Hedera
    - name: Install Protobuf Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Build docs
      run: cargo doc --no-deps
