name: Clippy

on: [push, pull_request]

jobs:
  clippy_check:
    name: check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # ADD THIS - Install protoc for Hedera
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
