on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Clippy

jobs:
  check:
    name: check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run clippy
        run: cargo clippy
