on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build docs

jobs:
  check:
    env: 
        RUSTDOCFLAGS: '-D warnings'
          
    name: check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check docs build
        run: cargo doc --no-deps
