name: Build docs

on: [push, pull_request]

jobs:
  check-docs:
    name: check docs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      
      # ADD THIS - Install protoc for Hedera
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
      - name: check docs
        run: cargo doc --no-deps
