on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Run all tests (including building doc tests and examples)

jobs:
  tests:
    name: check tests 
    runs-on: ubuntu-latest
    steps:

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.10

      - uses: actions/checkout@v3
      - name: Run all tests (including building doc tests and examples)
        run: cargo test
