on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Run all tests (including building doc tests and examples)

jobs:
  tests:
    name: check tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run all tests (including building doc tests and examples)
        run: cargo test
