name: Run all tests (including building doc tests and examples)

on: [push, pull_request]

jobs:
  test:
    name: check tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # ADD THIS - Install protoc for Hedera
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
      - name: test
        run: cargo test --verbose --all-features
        
      - name: test docs
        run: cargo test --doc --verbose --all-features
